## EDA on some gambling data!

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("restructuring_revenue_data.csv")

In [28]:
df

,Municipality,Establishment,License Number,VGT Count,Amount Played,Amount Won,Net Wager,Funds In,Funds Out,Net Terminal Income,NTI Tax,State Share,Municipality Share
0,Abingdon,ABBE LANES BOWLING & ENTERTAINMENT LLC,180702343.0,4.0,3295139.14,3025138.64,270000.50,950797.0,680796.93,270000.07,91519.07,78019.04,13500.03
1,Abingdon,AT'S Pub & Sport LLC,210700197.0,5.0,562807.01,529586.48,33220.53,187887.0,154666.47,33220.53,11295.04,9633.99,1661.05
2,Abingdon,"JP FOOD & LIQUOR , INC.",220701041.0,6.0,3435601.57,3117665.61,317935.96,1021427.0,703488.89,317938.11,108098.94,92202.04,15896.90
3,Abingdon,MA & PA LIQUOR'S INC.,200702153.0,6.0,9707785.70,8887964.96,819820.74,2764182.0,1944361.16,819820.84,278739.58,237748.51,40991.07
4,Abingdon,"Skeeter's Place, Inc.",120704053.0,5.0,3354301.99,3086378.16,267923.83,1148570.0,880644.42,267925.58,90807.98,77411.62,13396.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10307,Zion,"Northpointe Inn, Inc.",150702937.0,6.0,20155288.81,18433543.74,1721745.07,7109253.0,5387507.78,1721745.22,582983.29,496895.99,86087.30
10308,Zion,Qu's Place LLC,190700309.0,6.0,2632215.05,2418316.14,213898.91,1107429.0,893509.09,213919.91,72732.83,62036.83,10696.00
10309,Zion,SDD ENTERTAINMENT LLC,150703662.0,6.0,47645563.42,43342466.91,4303096.51,16025717.0,11722586.70,4303130.30,1456938.94,1241782.42,215156.52
10310,Zion,SDD ENTERTAINMENT LLC,150703712.0,6.0,51100349.16,46375287.32,4725061.84,16396697.0,11671634.16,4725062.84,1600387.34,1364134.17,236253.17
10311,Zion,STAR 6855 INCORPORATED,170702931.0,6.0,16129681.03,14733315.25,1396365.78,5645662.0,4249296.22,1396365.78,472417.26,402598.99,69818.27